### ISSUE TITLE
improve revenue forecasting model

### ISSUE THREAD

**Issue by deanmalmgren** [datascopeanalytics/a-model#2]
Drawing uniformly at random from recent historical revenues is v stupid but a good starting point. We have a lot more information than that, including expected revenues in accounts receivable (available in quickbooks), projected revenues from projects underway (available from P&L google doc or trello), and prospective revenues from our sales pipeline (trello). It would be nice to come up with a better revenue forecasting model that was smarter so we could make more reasonable projections than what we're doing with our current `hiring_confidence.py` and `estimate_bonuses.py` scripts today.

**Comment by deanmalmgren** [comment]
@stringertheory i think your fix in #1 goes a long way toward addressing this issue, too. i think it would be pretty awesome to integrate something from trello on this, too

**Comment by stringertheory** [comment]
That would be awesome to incorporate the pipeline! I don't think it would be too hard to do, but if we wanted to it might make sense to put labels that estimate time scales on different cards.

**Comment by stringertheory** [comment]
I just made a change so that there is no additional revenue added for the next three months (we know whether or not we've sent an invoice). I think the revenue projection is quite a bit more accurate with that. We might also want to include a term that accounts for p(late payment), which would make these a bit less rosy (and also more accurate).

**Comment by deanmalmgren** [comment]
Our current model is a step closer to this. From quickbooks, we download our P&L and outstanding unpaid invoices. We then combine this with our projected revenues from signed projects and simulate the process of getting our invoices paid combined with finishing current work in progress. 

The last thing remaining is to introduce revenue from our sales pipeline, perhaps from the 'finalize' and 'proposal process' columns of our trello board.

**Comment by stringertheory** [comment]
The recent issues on the board reminded me about this one. I think it's probably pretty important to include payment time variability (late payments, the v. rare early payment) in our revenue forecasts. I find myself not trusting the end of year bonus projections as much (especially on the high side) because of that.

**Comment by deanmalmgren** [comment]
we account for two sources of noise in [our current revenue forecasting](https://github.com/datascopeanalytics/a-model/blob/master/a_model/datascope.py#L139-L187): late payment and tardy work completion :) this is getting there!

**Comment by stringertheory** [comment]
awesome!

## 

_mike stringer | partner | *_datascope*
http://datascopeanalytics.com
cell: +1.773.319.7223

**Comment by deanmalmgren** [comment]
Now that #20 exists, I think we can safely close this one.
